// lib/wc2026-data.ts
// World Cup 2026 — players from provided list with country assignments

export const WC2026_TEAMS = [
  "Algeria", "Argentina", "Australia", "Austria",
  "Belgium", "Bosnia and Herzegovina", "Brazil",
  "Canada", "Cape Verde", "Colombia", "Congo DR", "Croatia", "Curacao", "Czechia",
  "Ecuador", "Egypt", "England",
  "France",
  "Germany", "Ghana",
  "Haiti",
  "Iran", "Iraq", "Ivory Coast",
  "Japan", "Jordan",
  "Mexico", "Morocco",
  "Netherlands", "New Zealand", "Norway",
  "Panama", "Paraguay", "Portugal",
  "Qatar",
  "Saudi Arabia", "Scotland", "Senegal", "South Africa", "South Korea", "Spain", "Sweden", "Switzerland",
  "Tunisia", "Turkey",
  "United States", "Uruguay", "Uzbekistan",
];

export const WC2026_SCORERS: { code: string; country: string; player: string }[] = [
  // Algeria
  { code: "ALG", country: "Algeria", player: "Amoura, Mohammed" },
  { code: "ALG", country: "Algeria", player: "Bounedjah, Baghdad" },
  { code: "ALG", country: "Algeria", player: "Gouiri, Amine" },
  { code: "ALG", country: "Algeria", player: "Igamane, Hamza" },
  { code: "ALG", country: "Algeria", player: "Mahrez, Riyad" },
  // Argentina
  { code: "ARG", country: "Argentina", player: "Álvarez, Julián" },
  { code: "ARG", country: "Argentina", player: "Correa, Ángel" },
  { code: "ARG", country: "Argentina", player: "Dybala, Paulo" },
  { code: "ARG", country: "Argentina", player: "González, Nicolás" },
  { code: "ARG", country: "Argentina", player: "Lautaro Martínez" },
  { code: "ARG", country: "Argentina", player: "Messi, Lionel" },
  { code: "ARG", country: "Argentina", player: "Pellistri, Facundo" },
  { code: "ARG", country: "Argentina", player: "Simeone, Giuliano" },
  // Australia
  { code: "AUS", country: "Australia", player: "Boyle, Martin" },
  { code: "AUS", country: "Australia", player: "Duke, Mitchell" },
  { code: "AUS", country: "Australia", player: "Goodwin, Craig" },
  { code: "AUS", country: "Australia", player: "Irankunda, Nestory" },
  { code: "AUS", country: "Australia", player: "Irvine, Jackson" },
  { code: "AUS", country: "Australia", player: "Taggart, Adam" },
  { code: "AUS", country: "Australia", player: "Weimann, Andreas" },
  { code: "AUS", country: "Australia", player: "Yengi, Kusini" },
  // Austria
  { code: "AUT", country: "Austria", player: "Arnautovic, Marko" },
  { code: "AUT", country: "Austria", player: "Baumgartner, Christoph" },
  { code: "AUT", country: "Austria", player: "Gregoritsch, Michael" },
  { code: "AUT", country: "Austria", player: "Sabitzer, Marcel" },
  { code: "AUT", country: "Austria", player: "Schopf, Alessandro" },
  // Belgium
  { code: "BEL", country: "Belgium", player: "Batshuayi, Michy" },
  { code: "BEL", country: "Belgium", player: "De Bruyne, Kevin" },
  { code: "BEL", country: "Belgium", player: "Doku, Jeremy" },
  { code: "BEL", country: "Belgium", player: "Lukaku, Romelu" },
  { code: "BEL", country: "Belgium", player: "Lukebakio, Dodi" },
  { code: "BEL", country: "Belgium", player: "Openda, Loïs" },
  { code: "BEL", country: "Belgium", player: "Trossard, Leandro" },
  // Bosnia and Herzegovina
  { code: "BIH", country: "Bosnia and Herzegovina", player: "Demirovic, Ermedin" },
  { code: "BIH", country: "Bosnia and Herzegovina", player: "Dzeko, Edin" },
  { code: "BIH", country: "Bosnia and Herzegovina", player: "Ivanovic, Franjo" },
  { code: "BIH", country: "Bosnia and Herzegovina", player: "Petkovic, Bruno" },
  { code: "BIH", country: "Bosnia and Herzegovina", player: "Tabakovic, Haris" },
  // Brazil
  { code: "BRA", country: "Brazil", player: "Antony" },
  { code: "BRA", country: "Brazil", player: "Cunha, Matheus" },
  { code: "BRA", country: "Brazil", player: "Endrick" },
  { code: "BRA", country: "Brazil", player: "Estevao Willian" },
  { code: "BRA", country: "Brazil", player: "Luiz Henrique" },
  { code: "BRA", country: "Brazil", player: "Martinelli, Gabriel" },
  { code: "BRA", country: "Brazil", player: "Neymar" },
  { code: "BRA", country: "Brazil", player: "Raphinha" },
  { code: "BRA", country: "Brazil", player: "Richarlison" },
  { code: "BRA", country: "Brazil", player: "Savinho" },
  { code: "BRA", country: "Brazil", player: "Vinicius Jr." },
  // Canada
  { code: "CAN", country: "Canada", player: "Aaronson, Brenden" },
  { code: "CAN", country: "Canada", player: "Cavallini, Lucas" },
  { code: "CAN", country: "Canada", player: "David, Jonathan" },
  { code: "CAN", country: "Canada", player: "Davies, Alphonso" },
  { code: "CAN", country: "Canada", player: "Larin, Cyle" },
  { code: "CAN", country: "Canada", player: "Nelson, Jayden" },
  // Cape Verde
  { code: "CPV", country: "Cape Verde", player: "Mendes, Ryan" },
  { code: "CPV", country: "Cape Verde", player: "Rodrigues, Garry" },
  // Colombia
  { code: "COL", country: "Colombia", player: "Arias, Jhon" },
  { code: "COL", country: "Colombia", player: "Carbonero, Johan" },
  { code: "COL", country: "Colombia", player: "Córdoba, Jhon" },
  { code: "COL", country: "Colombia", player: "Díaz, Luis" },
  { code: "COL", country: "Colombia", player: "Durán, Jhon" },
  { code: "COL", country: "Colombia", player: "James Rodríguez" },
  { code: "COL", country: "Colombia", player: "Quiñones, Julián" },
  { code: "COL", country: "Colombia", player: "Sinisterra, Luis" },
  { code: "COL", country: "Colombia", player: "Suárez, Luis Javier" },
  // Congo DR
  { code: "COD", country: "Congo DR", player: "Bakambu, Cédric" },
  { code: "COD", country: "Congo DR", player: "Diallo, Amas" },
  { code: "COD", country: "Congo DR", player: "Mayele, Fiston" },
  { code: "COD", country: "Congo DR", player: "Wissa, Yoane" },
  // Croatia
  { code: "CRO", country: "Croatia", player: "Budimir, Ante" },
  { code: "CRO", country: "Croatia", player: "Ivanovic, Franjo" },
  { code: "CRO", country: "Croatia", player: "Kramarić, Andrej" },
  { code: "CRO", country: "Croatia", player: "Modrić, Luka" },
  { code: "CRO", country: "Croatia", player: "Orsić, Mislav" },
  { code: "CRO", country: "Croatia", player: "Pasalić, Marco" },
  { code: "CRO", country: "Croatia", player: "Perišić, Ivan" },
  { code: "CRO", country: "Croatia", player: "Vlašić, Nikola" },
  // Curacao
  { code: "CUW", country: "Curacao", player: "Gorre, Kenji" },
  { code: "CUW", country: "Curacao", player: "Margaritha, Jearel" },
  // Czechia
  { code: "CZE", country: "Czechia", player: "Chory, Tomáš" },
  { code: "CZE", country: "Czechia", player: "Chytil, Filip" },
  { code: "CZE", country: "Czechia", player: "Hirst, George" },
  { code: "CZE", country: "Czechia", player: "Matanovic, Igor" },
  { code: "CZE", country: "Czechia", player: "Schick, Patrik" },
  // Ecuador
  { code: "ECU", country: "Ecuador", player: "Caicedo, Moisés" },
  { code: "ECU", country: "Ecuador", player: "Plata, Gonzalo" },
  { code: "ECU", country: "Ecuador", player: "Torres, Félix" },
  { code: "ECU", country: "Ecuador", player: "Valencia, Enner" },
  // Egypt
  { code: "EGY", country: "Egypt", player: "El Kaabi, Ayoub" },
  { code: "EGY", country: "Egypt", player: "Elneny, Mohamed" },
  { code: "EGY", country: "Egypt", player: "Marmoush, Omar" },
  { code: "EGY", country: "Egypt", player: "Mostafa Mohamed" },
  { code: "EGY", country: "Egypt", player: "Salah, Mohamed" },
  { code: "EGY", country: "Egypt", player: "Trezeguet" },
  // England
  { code: "ENG", country: "England", player: "Bellingham, Jude" },
  { code: "ENG", country: "England", player: "Calvert-Lewin, Dominic" },
  { code: "ENG", country: "England", player: "Eze, Eberechi" },
  { code: "ENG", country: "England", player: "Foden, Phil" },
  { code: "ENG", country: "England", player: "Gordon, Anthony" },
  { code: "ENG", country: "England", player: "Kane, Harry" },
  { code: "ENG", country: "England", player: "Madueke, Noni" },
  { code: "ENG", country: "England", player: "Palmer, Cole" },
  { code: "ENG", country: "England", player: "Rashford, Marcus" },
  { code: "ENG", country: "England", player: "Rice, Declan" },
  { code: "ENG", country: "England", player: "Rogers, Morgan" },
  { code: "ENG", country: "England", player: "Saka, Bukayo" },
  { code: "ENG", country: "England", player: "Semenyo, Antoine" },
  { code: "ENG", country: "England", player: "Solanke, Dominic" },
  { code: "ENG", country: "England", player: "Watkins, Ollie" },
  // France
  { code: "FRA", country: "France", player: "Barcola, Bradley" },
  { code: "FRA", country: "France", player: "Camavinga, Eduardo" },
  { code: "FRA", country: "France", player: "Coman, Kingsley" },
  { code: "FRA", country: "France", player: "Dembélé, Ousmane" },
  { code: "FRA", country: "France", player: "Doué, Désiré" },
  { code: "FRA", country: "France", player: "Griezmann, Antoine" },
  { code: "FRA", country: "France", player: "Mbappé, Kylian" },
  { code: "FRA", country: "France", player: "Muani, Randal" },
  { code: "FRA", country: "France", player: "Nkunku, Christopher" },
  { code: "FRA", country: "France", player: "Thuram, Marcus" },
  // Germany
  { code: "GER", country: "Germany", player: "Adeyemi, Karim" },
  { code: "GER", country: "Germany", player: "Beier, Maximilian" },
  { code: "GER", country: "Germany", player: "Brandt, Julian" },
  { code: "GER", country: "Germany", player: "Havertz, Kai" },
  { code: "GER", country: "Germany", player: "Kleindienst, Tim" },
  { code: "GER", country: "Germany", player: "Musiala, Jamal" },
  { code: "GER", country: "Germany", player: "Undav, Deniz" },
  { code: "GER", country: "Germany", player: "Wirtz, Florian" },
  { code: "GER", country: "Germany", player: "Woltemade, Nick" },
  // Ghana
  { code: "GHA", country: "Ghana", player: "Ayew, Jordan" },
  { code: "GHA", country: "Ghana", player: "Fatawu, Issahaku" },
  { code: "GHA", country: "Ghana", player: "Foster, Lyle" },
  { code: "GHA", country: "Ghana", player: "Kudus, Mohammed" },
  { code: "GHA", country: "Ghana", player: "Nuamah, Ernest" },
  { code: "GHA", country: "Ghana", player: "Sulemana, Kamaldeen" },
  // Haiti
  { code: "HAI", country: "Haiti", player: "Etienne Jr., Derrick" },
  { code: "HAI", country: "Haiti", player: "Louicius, Don Deedson" },
  { code: "HAI", country: "Haiti", player: "Nazon, Duckens" },
  { code: "HAI", country: "Haiti", player: "Pierrot, Frantzdy" },
  // Iran
  { code: "IRN", country: "Iran", player: "Alipour, Ali" },
  { code: "IRN", country: "Iran", player: "Azmoun, Sardar" },
  { code: "IRN", country: "Iran", player: "Jahanbakhsh, Alireza" },
  { code: "IRN", country: "Iran", player: "Taremi, Mehdi" },
  // Iraq
  { code: "IRQ", country: "Iraq", player: "Al Rawi, Ahmed" },
  { code: "IRQ", country: "Iraq", player: "Alaaeldin, Ahmed" },
  { code: "IRQ", country: "Iraq", player: "Al Hamadi, Ali" },
  { code: "IRQ", country: "Iraq", player: "Hussein, Aymen" },
  { code: "IRQ", country: "Iraq", player: "Mohanad Ali" },
  // Ivory Coast
  { code: "CIV", country: "Ivory Coast", player: "Adingra, Simon" },
  { code: "CIV", country: "Ivory Coast", player: "Diallo, Habib" },
  { code: "CIV", country: "Ivory Coast", player: "Haller, Sébastien" },
  { code: "CIV", country: "Ivory Coast", player: "Pépé, Nicolas" },
  { code: "CIV", country: "Ivory Coast", player: "Zaha, Wilfried" },
  // Japan
  { code: "JPN", country: "Japan", player: "Furuhashi, Kyogo" },
  { code: "JPN", country: "Japan", player: "Hosoya, Mao" },
  { code: "JPN", country: "Japan", player: "Kamada, Daichi" },
  { code: "JPN", country: "Japan", player: "Kubo, Takefusa" },
  { code: "JPN", country: "Japan", player: "Machino, Shuto" },
  { code: "JPN", country: "Japan", player: "Maeda, Daizen" },
  { code: "JPN", country: "Japan", player: "Mitoma, Kaoru" },
  { code: "JPN", country: "Japan", player: "Ogawa, Koki" },
  { code: "JPN", country: "Japan", player: "Ueda, Ayase" },
  // Jordan
  { code: "JOR", country: "Jordan", player: "Al Taamari, Musa" },
  { code: "JOR", country: "Jordan", player: "Al Naimat, Yazan" },
  // Mexico
  { code: "MEX", country: "Mexico", player: "Alvarado, Roberto" },
  { code: "MEX", country: "Mexico", player: "Giménez, Santiago" },
  { code: "MEX", country: "Mexico", player: "Guerrero, Eduardo" },
  { code: "MEX", country: "Mexico", player: "Lozano, Hirving" },
  { code: "MEX", country: "Mexico", player: "Pineda, Orbelin" },
  { code: "MEX", country: "Mexico", player: "Raúl Jiménez" },
  { code: "MEX", country: "Mexico", player: "Rodríguez, Kevin" },
  { code: "MEX", country: "Mexico", player: "Vega, Alexis" },
  // Morocco
  { code: "MAR", country: "Morocco", player: "Aboukhlal, Zakaria" },
  { code: "MAR", country: "Morocco", player: "Boufal, Sofiane" },
  { code: "MAR", country: "Morocco", player: "Diaz, Brahim" },
  { code: "MAR", country: "Morocco", player: "En-Nesyri, Youssef" },
  { code: "MAR", country: "Morocco", player: "Hakimi, Achraf" },
  { code: "MAR", country: "Morocco", player: "Rahimi, Soufiane" },
  { code: "MAR", country: "Morocco", player: "Ziyech, Hakim" },
  // Netherlands
  { code: "NED", country: "Netherlands", player: "Brobbey, Brian" },
  { code: "NED", country: "Netherlands", player: "Depay, Memphis" },
  { code: "NED", country: "Netherlands", player: "Dumfries, Denzel" },
  { code: "NED", country: "Netherlands", player: "Gakpo, Cody" },
  { code: "NED", country: "Netherlands", player: "Kluivert, Justin" },
  { code: "NED", country: "Netherlands", player: "Lang, Noa" },
  { code: "NED", country: "Netherlands", player: "Malen, Donyell" },
  { code: "NED", country: "Netherlands", player: "Reijnders, Tijjani" },
  { code: "NED", country: "Netherlands", player: "Simons, Xavi" },
  { code: "NED", country: "Netherlands", player: "Weghorst, Wout" },
  { code: "NED", country: "Netherlands", player: "Zirkzee, Joshua" },
  // New Zealand
  { code: "NZL", country: "New Zealand", player: "Waine, Ben" },
  { code: "NZL", country: "New Zealand", player: "Wood, Chris" },
  // Norway
  { code: "NOR", country: "Norway", player: "Bobb, Oscar" },
  { code: "NOR", country: "Norway", player: "Haaland, Erling" },
  { code: "NOR", country: "Norway", player: "King, Joshua" },
  { code: "NOR", country: "Norway", player: "Nusa, Antonio" },
  { code: "NOR", country: "Norway", player: "Ødegaard, Martin" },
  { code: "NOR", country: "Norway", player: "Sørloth, Alexander" },
  { code: "NOR", country: "Norway", player: "Thorstvedt, Kristian" },
  // Panama
  { code: "PAN", country: "Panama", player: "Fajardo, José" },
  { code: "PAN", country: "Panama", player: "Gonzalez, Armando" },
  { code: "PAN", country: "Panama", player: "Laquintana, Ignacio" },
  { code: "PAN", country: "Panama", player: "Waterman, Cecilio" },
  // Paraguay
  { code: "PAR", country: "Paraguay", player: "Almiron, Miguel" },
  { code: "PAR", country: "Paraguay", player: "Avalos, Gabriel" },
  { code: "PAR", country: "Paraguay", player: "Enciso, Julio" },
  { code: "PAR", country: "Paraguay", player: "Romero, Ángel" },
  { code: "PAR", country: "Paraguay", player: "Sanabria, Antonio" },
  { code: "PAR", country: "Paraguay", player: "Viñas, Federico" },
  // Portugal
  { code: "POR", country: "Portugal", player: "Bernardo Silva" },
  { code: "POR", country: "Portugal", player: "Bruno Fernandes" },
  { code: "POR", country: "Portugal", player: "Félix, João" },
  { code: "POR", country: "Portugal", player: "Gonçalo Ramos" },
  { code: "POR", country: "Portugal", player: "Leão, Rafael" },
  { code: "POR", country: "Portugal", player: "Neves, João" },
  { code: "POR", country: "Portugal", player: "Neto, Pedro" },
  { code: "POR", country: "Portugal", player: "Ronaldo, Cristiano" },
  // Qatar
  { code: "QAT", country: "Qatar", player: "Afif, Akram" },
  { code: "QAT", country: "Qatar", player: "Ali, Almoez" },
  { code: "QAT", country: "Qatar", player: "Muntari, Mohammed" },
  // Saudi Arabia
  { code: "KSA", country: "Saudi Arabia", player: "Al Buraikan, Firas" },
  { code: "KSA", country: "Saudi Arabia", player: "Al Dawsari, Salem" },
  { code: "KSA", country: "Saudi Arabia", player: "Al Hamdan, Abdullah" },
  { code: "KSA", country: "Saudi Arabia", player: "Al Shehri, Saleh" },
  // Scotland
  { code: "SCO", country: "Scotland", player: "Adams, Che" },
  { code: "SCO", country: "Scotland", player: "Christie, Ryan" },
  { code: "SCO", country: "Scotland", player: "Dykes, Lyndon" },
  { code: "SCO", country: "Scotland", player: "McGinn, John" },
  { code: "SCO", country: "Scotland", player: "McTominay, Scott" },
  { code: "SCO", country: "Scotland", player: "Shankland, Lawrence" },
  // Senegal
  { code: "SEN", country: "Senegal", player: "Dia, Boulaye" },
  { code: "SEN", country: "Senegal", player: "Diallo, Habib" },
  { code: "SEN", country: "Senegal", player: "Mané, Sadio" },
  { code: "SEN", country: "Senegal", player: "Sarr, Ismaila" },
  // South Africa
  { code: "RSA", country: "South Africa", player: "Foster, Lyle" },
  { code: "RSA", country: "South Africa", player: "Rayners, Iqraam" },
  // South Korea
  { code: "KOR", country: "South Korea", player: "Cho, Gue-sung" },
  { code: "KOR", country: "South Korea", player: "Hwang, Hee-chan" },
  { code: "KOR", country: "South Korea", player: "Kang-In Lee" },
  { code: "KOR", country: "South Korea", player: "Oh, Hyeon-gyu" },
  { code: "KOR", country: "South Korea", player: "Son, Heung-min" },
  // Spain
  { code: "ESP", country: "Spain", player: "Dani Olmo" },
  { code: "ESP", country: "Spain", player: "Fabian Ruiz" },
  { code: "ESP", country: "Spain", player: "Ferran Torres" },
  { code: "ESP", country: "Spain", player: "Isco" },
  { code: "ESP", country: "Spain", player: "Merino, Mikel" },
  { code: "ESP", country: "Spain", player: "Morata, Álvaro" },
  { code: "ESP", country: "Spain", player: "Olise, Michael" },
  { code: "ESP", country: "Spain", player: "Oyarzabal, Mikel" },
  { code: "ESP", country: "Spain", player: "Pedri" },
  { code: "ESP", country: "Spain", player: "Williams, Nico" },
  { code: "ESP", country: "Spain", player: "Yamal, Lamine" },
  // Sweden
  { code: "SWE", country: "Sweden", player: "Elanga, Anthony" },
  { code: "SWE", country: "Sweden", player: "Gyökeres, Viktor" },
  { code: "SWE", country: "Sweden", player: "Isak, Alexander" },
  { code: "SWE", country: "Sweden", player: "Kulusevski, Dejan" },
  { code: "SWE", country: "Sweden", player: "Larsen, Jörgen" },
  { code: "SWE", country: "Sweden", player: "Nygren, Benjamin" },
  // Switzerland
  { code: "SUI", country: "Switzerland", player: "Amdouni, Zeki" },
  { code: "SUI", country: "Switzerland", player: "Embolo, Breel" },
  { code: "SUI", country: "Switzerland", player: "Itten, Cédric" },
  { code: "SUI", country: "Switzerland", player: "Ndoye, Dan" },
  { code: "SUI", country: "Switzerland", player: "Vargas, Ruben" },
  // Tunisia
  { code: "TUN", country: "Tunisia", player: "Chaouat, Firas" },
  { code: "TUN", country: "Tunisia", player: "Jaziri, Seifeddine" },
  { code: "TUN", country: "Tunisia", player: "Mastouri, Hazem" },
  { code: "TUN", country: "Tunisia", player: "Msakni, Youssef" },
  { code: "TUN", country: "Tunisia", player: "Sliti, Naim" },
  // Turkey
  { code: "TUR", country: "Turkey", player: "Akturkoglu, Kerem" },
  { code: "TUR", country: "Turkey", player: "Calhanoglu, Hakan" },
  { code: "TUR", country: "Turkey", player: "Güler, Arda" },
  { code: "TUR", country: "Turkey", player: "Yıldız, Kenan" },
  // United States
  { code: "USA", country: "United States", player: "Aaronson, Brenden" },
  { code: "USA", country: "United States", player: "Balogun, Folarin" },
  { code: "USA", country: "United States", player: "Pepi, Ricardo" },
  { code: "USA", country: "United States", player: "Pulisic, Christian" },
  { code: "USA", country: "United States", player: "Reyna, Giovanni" },
  { code: "USA", country: "United States", player: "Sargent, Josh" },
  { code: "USA", country: "United States", player: "Weah, Tim" },
  { code: "USA", country: "United States", player: "Wright, Haji" },
  // Uruguay
  { code: "URU", country: "Uruguay", player: "Aguirre, Rodrigo" },
  { code: "URU", country: "Uruguay", player: "De Arrascaeta, Giorgian" },
  { code: "URU", country: "Uruguay", player: "Núñez, Darwin" },
  { code: "URU", country: "Uruguay", player: "Suárez, Luis" },
  { code: "URU", country: "Uruguay", player: "Torres, Facundo" },
  { code: "URU", country: "Uruguay", player: "Valverde, Federico" },
  // Uzbekistan
  { code: "UZB", country: "Uzbekistan", player: "Shomurodov, Eldor" },
];

export function formatScorer(s: { code: string; player: string }): string {
  return `(${s.code}) ${s.player}`;
}
