// lib/wc2026-data.ts
// World Cup 2026 — teams and top scorer candidates
// Updated April 2026 — injured/inactive players removed

export const WC2026_TEAMS = [
  "Algeria", "Argentina", "Australia", "Austria",
  "Belgium", "Bosnia and Herzegovina", "Brazil",
  "Canada", "Cape Verde", "Colombia", "Congo DR", "Croatia", "Curacao", "Czechia",
  "Ecuador", "Egypt", "England",
  "France",
  "Germany", "Ghana",
  "Haiti",
  "Iran", "Iraq", "Ivory Coast",
  "Japan", "Jordan",
  "Mexico", "Morocco",
  "Netherlands", "New Zealand", "Norway",
  "Panama", "Paraguay", "Portugal",
  "Qatar",
  "Saudi Arabia", "Scotland", "Senegal", "South Africa", "South Korea", "Spain", "Sweden", "Switzerland",
  "Tunisia", "Turkey",
  "United States", "Uruguay", "Uzbekistan",
];

export const WC2026_SCORERS: { code: string; country: string; player: string }[] = [
  // Algeria
  { code: "ALG", country: "Algeria", player: "Belaili, Youcef" },
  { code: "ALG", country: "Algeria", player: "Bennacer, Ismael" },
  { code: "ALG", country: "Algeria", player: "Bounedjah, Baghdad" },
  { code: "ALG", country: "Algeria", player: "Mahrez, Riyad" },
  { code: "ALG", country: "Algeria", player: "Slimani, Islam" },
  // Argentina
  { code: "ARG", country: "Argentina", player: "Álvarez, Julián" },
  { code: "ARG", country: "Argentina", player: "Di María, Ángel" },
  { code: "ARG", country: "Argentina", player: "Dybala, Paulo" },
  { code: "ARG", country: "Argentina", player: "Lautaro Martínez" },
  { code: "ARG", country: "Argentina", player: "Messi, Lionel" },
  // Australia
  { code: "AUS", country: "Australia", player: "Goodwin, Mitchell" },
  { code: "AUS", country: "Australia", player: "Irvine, Jackson" },
  { code: "AUS", country: "Australia", player: "Leckie, Mathew" },
  { code: "AUS", country: "Australia", player: "McGree, Riley" },
  { code: "AUS", country: "Australia", player: "Nisbet, Kyle" },
  // Austria
  { code: "AUT", country: "Austria", player: "Arnautovic, Marko" },
  { code: "AUT", country: "Austria", player: "Baumgartner, Christoph" },
  { code: "AUT", country: "Austria", player: "Gregoritsch, Michael" },
  { code: "AUT", country: "Austria", player: "Sabitzer, Marcel" },
  { code: "AUT", country: "Austria", player: "Wimmer, Patrick" },
  // Belgium
  { code: "BEL", country: "Belgium", player: "De Bruyne, Kevin" },
  { code: "BEL", country: "Belgium", player: "Doku, Jeremy" },
  { code: "BEL", country: "Belgium", player: "Lukaku, Romelu" },
  { code: "BEL", country: "Belgium", player: "Openda, Loïs" },
  { code: "BEL", country: "Belgium", player: "Trossard, Leandro" },
  // Bosnia and Herzegovina
  { code: "BIH", country: "Bosnia and Herzegovina", player: "Dzeko, Edin" },
  { code: "BIH", country: "Bosnia and Herzegovina", player: "Gazibegovic, Sead" },
  { code: "BIH", country: "Bosnia and Herzegovina", player: "Hajradinovic, Haris" },
  { code: "BIH", country: "Bosnia and Herzegovina", player: "Prevljak, Ermedin" },
  { code: "BIH", country: "Bosnia and Herzegovina", player: "Stevanovic, Anel" },
  // Brazil — Neymar included per request, Rodrygo OUT (ACL)
  { code: "BRA", country: "Brazil", player: "Endrick" },
  { code: "BRA", country: "Brazil", player: "Neymar Jr." },
  { code: "BRA", country: "Brazil", player: "Raphinha" },
  { code: "BRA", country: "Brazil", player: "Savinho" },
  { code: "BRA", country: "Brazil", player: "Vinicius Jr." },
  // Canada
  { code: "CAN", country: "Canada", player: "Buchanan, Tajon" },
  { code: "CAN", country: "Canada", player: "David, Jonathan" },
  { code: "CAN", country: "Canada", player: "Davies, Alphonso" },
  { code: "CAN", country: "Canada", player: "Eustaquio, Stephen" },
  { code: "CAN", country: "Canada", player: "Larin, Cyle" },
  // Cape Verde
  { code: "CPV", country: "Cape Verde", player: "Andrade, Ryan" },
  { code: "CPV", country: "Cape Verde", player: "Pina, Jamiro" },
  { code: "CPV", country: "Cape Verde", player: "Rodrigues, Kenny" },
  { code: "CPV", country: "Cape Verde", player: "Soares, Diogo" },
  { code: "CPV", country: "Cape Verde", player: "Tavares, Garry" },
  // Colombia
  { code: "COL", country: "Colombia", player: "Díaz, Luis" },
  { code: "COL", country: "Colombia", player: "Durán, Jhon" },
  { code: "COL", country: "Colombia", player: "James Rodríguez" },
  { code: "COL", country: "Colombia", player: "Morelos, Alfredo" },
  { code: "COL", country: "Colombia", player: "Suárez, Rafael" },
  // Congo DR
  { code: "COD", country: "Congo DR", player: "Bongonda, Théo" },
  { code: "COD", country: "Congo DR", player: "Bolasie, Yala" },
  { code: "COD", country: "Congo DR", player: "Kayembe, Edo" },
  { code: "COD", country: "Congo DR", player: "Lualaba, Arthur" },
  { code: "COD", country: "Congo DR", player: "Mbokani, Dieumerci" },
  // Croatia
  { code: "CRO", country: "Croatia", player: "Budimir, Ante" },
  { code: "CRO", country: "Croatia", player: "Kramarić, Andrej" },
  { code: "CRO", country: "Croatia", player: "Modrić, Luka" },
  { code: "CRO", country: "Croatia", player: "Pasalić, Mario" },
  { code: "CRO", country: "Croatia", player: "Perišić, Ivan" },
  // Curacao
  { code: "CUW", country: "Curacao", player: "Amorimella, Myron" },
  { code: "CUW", country: "Curacao", player: "Cijntje, Cuco" },
  { code: "CUW", country: "Curacao", player: "Dos Santos, Leandro" },
  { code: "CUW", country: "Curacao", player: "Fer, Leroy" },
  { code: "CUW", country: "Curacao", player: "Sulvaran, Elson" },
  // Czechia
  { code: "CZE", country: "Czechia", player: "Chytil, Filip" },
  { code: "CZE", country: "Czechia", player: "Hlozek, Adam" },
  { code: "CZE", country: "Czechia", player: "Kuchta, Jan" },
  { code: "CZE", country: "Czechia", player: "Schick, Patrik" },
  { code: "CZE", country: "Czechia", player: "Souček, Tomáš" },
  // Ecuador
  { code: "ECU", country: "Ecuador", player: "Caicedo, Moisés" },
  { code: "ECU", country: "Ecuador", player: "Estrada, Enner" },
  { code: "ECU", country: "Ecuador", player: "Hincapié, Piero" },
  { code: "ECU", country: "Ecuador", player: "Plata, Gonzalo" },
  { code: "ECU", country: "Ecuador", player: "Valencia, Michael" },
  // Egypt — Salah doubtful but included
  { code: "EGY", country: "Egypt", player: "Marmoush, Omar" },
  { code: "EGY", country: "Egypt", player: "Mostafa Mohamed" },
  { code: "EGY", country: "Egypt", player: "Salah, Mohamed" },
  { code: "EGY", country: "Egypt", player: "Trezeguet" },
  { code: "EGY", country: "Egypt", player: "Zizo, Mohamed" },
  // England
  { code: "ENG", country: "England", player: "Bellingham, Jude" },
  { code: "ENG", country: "England", player: "Foden, Phil" },
  { code: "ENG", country: "England", player: "Kane, Harry" },
  { code: "ENG", country: "England", player: "Palmer, Cole" },
  { code: "ENG", country: "England", player: "Saka, Bukayo" },
  // France — Ekitike OUT (Achilles)
  { code: "FRA", country: "France", player: "Camavinga, Eduardo" },
  { code: "FRA", country: "France", player: "Dembélé, Ousmane" },
  { code: "FRA", country: "France", player: "Doué, Désiré" },
  { code: "FRA", country: "France", player: "Griezmann, Antoine" },
  { code: "FRA", country: "France", player: "Mbappé, Kylian" },
  // Germany — Gnabry OUT (injured)
  { code: "GER", country: "Germany", player: "Füllkrug, Niclas" },
  { code: "GER", country: "Germany", player: "Havertz, Kai" },
  { code: "GER", country: "Germany", player: "Musiala, Jamal" },
  { code: "GER", country: "Germany", player: "Undav, Deniz" },
  { code: "GER", country: "Germany", player: "Wirtz, Florian" },
  // Ghana — Salisu OUT (ACL), Paintsil duplicate removed
  { code: "GHA", country: "Ghana", player: "Ayew, Jordan" },
  { code: "GHA", country: "Ghana", player: "Kudus, Mohammed" },
  { code: "GHA", country: "Ghana", player: "Ofori-Twumasi, Edwin" },
  { code: "GHA", country: "Ghana", player: "Sulemana, Kamaldeen" },
  { code: "GHA", country: "Ghana", player: "Williams, Inaki" },
  // Haiti
  { code: "HAI", country: "Haiti", player: "Antoine, Dénécheau" },
  { code: "HAI", country: "Haiti", player: "Borgela, Mechak" },
  { code: "HAI", country: "Haiti", player: "Nazon, Duckens" },
  { code: "HAI", country: "Haiti", player: "Pierre, Frantz" },
  { code: "HAI", country: "Haiti", player: "Saint-Lot, Frantzdy" },
  // Iran
  { code: "IRN", country: "Iran", player: "Azmoun, Sardar" },
  { code: "IRN", country: "Iran", player: "Ezatolahi, Saeid" },
  { code: "IRN", country: "Iran", player: "Jahanbakhsh, Alireza" },
  { code: "IRN", country: "Iran", player: "Nosrati, Ahmad" },
  { code: "IRN", country: "Iran", player: "Taremi, Mehdi" },
  // Iraq
  { code: "IRQ", country: "Iraq", player: "Al-Hamdani, Bashar" },
  { code: "IRQ", country: "Iraq", player: "Amjed Attwan" },
  { code: "IRQ", country: "Iraq", player: "Ayman Hussein" },
  { code: "IRQ", country: "Iraq", player: "Mohanad Ali" },
  { code: "IRQ", country: "Iraq", player: "Safaa Hadi" },
  // Ivory Coast
  { code: "CIV", country: "Ivory Coast", player: "Gradel, Max-Alain" },
  { code: "CIV", country: "Ivory Coast", player: "Haller, Sébastien" },
  { code: "CIV", country: "Ivory Coast", player: "Kessié, Franck" },
  { code: "CIV", country: "Ivory Coast", player: "Pépé, Nicolas" },
  { code: "CIV", country: "Ivory Coast", player: "Zaha, Wilfried" },
  // Japan — Minamino OUT (ACL)
  { code: "JPN", country: "Japan", player: "Doan, Ritsu" },
  { code: "JPN", country: "Japan", player: "Kamada, Daichi" },
  { code: "JPN", country: "Japan", player: "Kubo, Takefusa" },
  { code: "JPN", country: "Japan", player: "Mitoma, Kaoru" },
  { code: "JPN", country: "Japan", player: "Ueda, Ayase" },
  // Jordan
  { code: "JOR", country: "Jordan", player: "Ahmad Hamdan" },
  { code: "JOR", country: "Jordan", player: "Al-Taamari, Musa" },
  { code: "JOR", country: "Jordan", player: "Baha' Faisal" },
  { code: "JOR", country: "Jordan", player: "Omar Al-Dameeri" },
  { code: "JOR", country: "Jordan", player: "Yazan Al-Naimat" },
  // Mexico
  { code: "MEX", country: "Mexico", player: "Alvarado, Roberto" },
  { code: "MEX", country: "Mexico", player: "Antuna, Uriel" },
  { code: "MEX", country: "Mexico", player: "Lozano, Hirving" },
  { code: "MEX", country: "Mexico", player: "Raúl Jiménez" },
  { code: "MEX", country: "Mexico", player: "Santi Giménez" },
  // Morocco
  { code: "MAR", country: "Morocco", player: "Boufal, Sofiane" },
  { code: "MAR", country: "Morocco", player: "En-Nesyri, Youssef" },
  { code: "MAR", country: "Morocco", player: "Hakimi, Achraf" },
  { code: "MAR", country: "Morocco", player: "Sabiri, Abdelhamid" },
  { code: "MAR", country: "Morocco", player: "Ziyech, Hakim" },
  // Netherlands
  { code: "NED", country: "Netherlands", player: "Depay, Memphis" },
  { code: "NED", country: "Netherlands", player: "Gakpo, Cody" },
  { code: "NED", country: "Netherlands", player: "Simons, Xavi" },
  { code: "NED", country: "Netherlands", player: "Weghorst, Wout" },
  { code: "NED", country: "Netherlands", player: "Zirkzee, Joshua" },
  // New Zealand
  { code: "NZL", country: "New Zealand", player: "Just, Oli" },
  { code: "NZL", country: "New Zealand", player: "Lewis, Clayton" },
  { code: "NZL", country: "New Zealand", player: "Payne, Liberato" },
  { code: "NZL", country: "New Zealand", player: "Rova, Sarpreet" },
  { code: "NZL", country: "New Zealand", player: "Wood, Chris" },
  // Norway
  { code: "NOR", country: "Norway", player: "Elyounoussi, Mohamed" },
  { code: "NOR", country: "Norway", player: "Haaland, Erling" },
  { code: "NOR", country: "Norway", player: "King, Joshua" },
  { code: "NOR", country: "Norway", player: "Ødegaard, Martin" },
  { code: "NOR", country: "Norway", player: "Sørloth, Alexander" },
  // Panama
  { code: "PAN", country: "Panama", player: "Davis, Rolando" },
  { code: "PAN", country: "Panama", player: "Fajardo, Ismael" },
  { code: "PAN", country: "Panama", player: "Murillo, Maximiliano" },
  { code: "PAN", country: "Panama", player: "Torres, Cecilio" },
  { code: "PAN", country: "Panama", player: "Valoy, Gabriel" },
  // Paraguay
  { code: "PAR", country: "Paraguay", player: "Almiron, Miguel" },
  { code: "PAR", country: "Paraguay", player: "Cubas, Andrés" },
  { code: "PAR", country: "Paraguay", player: "Enciso, Julio" },
  { code: "PAR", country: "Paraguay", player: "Gómez, Julio" },
  { code: "PAR", country: "Paraguay", player: "Sanabria, Antonio" },
  // Portugal — Ronaldo included (active, 6th WC)
  { code: "POR", country: "Portugal", player: "Bernardo Silva" },
  { code: "POR", country: "Portugal", player: "Bruno Fernandes" },
  { code: "POR", country: "Portugal", player: "Felix, João" },
  { code: "POR", country: "Portugal", player: "Leão, Rafael" },
  { code: "POR", country: "Portugal", player: "Ronaldo, Cristiano" },
  // Qatar
  { code: "QAT", country: "Qatar", player: "Afif, Akram" },
  { code: "QAT", country: "Qatar", player: "Al-Ahrak, Hassan" },
  { code: "QAT", country: "Qatar", player: "Ali, Almoez" },
  { code: "QAT", country: "Qatar", player: "Hatem, Abdulaziz" },
  { code: "QAT", country: "Qatar", player: "Munir, Mohammed" },
  // Saudi Arabia
  { code: "KSA", country: "Saudi Arabia", player: "Al-Buraikan, Firas" },
  { code: "KSA", country: "Saudi Arabia", player: "Al-Dawsari, Salem" },
  { code: "KSA", country: "Saudi Arabia", player: "Al-Ghannam, Mohammed" },
  { code: "KSA", country: "Saudi Arabia", player: "Al-Shehri, Saleh" },
  { code: "KSA", country: "Saudi Arabia", player: "Kanno, Mohamed" },
  // Scotland
  { code: "SCO", country: "Scotland", player: "Adams, Che" },
  { code: "SCO", country: "Scotland", player: "Christie, Ryan" },
  { code: "SCO", country: "Scotland", player: "Dykes, Lyndon" },
  { code: "SCO", country: "Scotland", player: "McGinn, John" },
  { code: "SCO", country: "Scotland", player: "McTominay, Scott" },
  // Senegal
  { code: "SEN", country: "Senegal", player: "Dia, Boulaye" },
  { code: "SEN", country: "Senegal", player: "Diatta, Lamine" },
  { code: "SEN", country: "Senegal", player: "Diedhiou, Famara" },
  { code: "SEN", country: "Senegal", player: "Mané, Sadio" },
  { code: "SEN", country: "Senegal", player: "Sarr, Ismaila" },
  // South Africa
  { code: "RSA", country: "South Africa", player: "Dolly, Keagan" },
  { code: "RSA", country: "South Africa", player: "Maja, Lebo" },
  { code: "RSA", country: "South Africa", player: "Monyane, Sphephelo" },
  { code: "RSA", country: "South Africa", player: "Mothiba, Lebo" },
  { code: "RSA", country: "South Africa", player: "Zwane, Themba" },
  // South Korea
  { code: "KOR", country: "South Korea", player: "Cho, Gue-sung" },
  { code: "KOR", country: "South Korea", player: "Hwang, Hee-chan" },
  { code: "KOR", country: "South Korea", player: "Lee, Jae-sung" },
  { code: "KOR", country: "South Korea", player: "Oh, Hyeon-gyu" },
  { code: "KOR", country: "South Korea", player: "Son, Heung-min" },
  // Spain — Yamal doubtful but expected fit, Samu Aghehowa OUT (ACL)
  { code: "ESP", country: "Spain", player: "Joselu" },
  { code: "ESP", country: "Spain", player: "Morata, Álvaro" },
  { code: "ESP", country: "Spain", player: "Olmo, Dani" },
  { code: "ESP", country: "Spain", player: "Williams, Nico" },
  { code: "ESP", country: "Spain", player: "Yamal, Lamine" },
  // Sweden
  { code: "SWE", country: "Sweden", player: "Forsberg, Emil" },
  { code: "SWE", country: "Sweden", player: "Gyökeres, Viktor" },
  { code: "SWE", country: "Sweden", player: "Isak, Alexander" },
  { code: "SWE", country: "Sweden", player: "Kulusevski, Dejan" },
  { code: "SWE", country: "Sweden", player: "Larsson, Jordan" },
  // Switzerland
  { code: "SUI", country: "Switzerland", player: "Amdouni, Zeki" },
  { code: "SUI", country: "Switzerland", player: "Embolo, Breel" },
  { code: "SUI", country: "Switzerland", player: "Ndoye, Dan" },
  { code: "SUI", country: "Switzerland", player: "Vargas, Ruben" },
  { code: "SUI", country: "Switzerland", player: "Zuber, Steven" },
  // Tunisia
  { code: "TUN", country: "Tunisia", player: "Ben Romdhane, Hannibal" },
  { code: "TUN", country: "Tunisia", player: "Jaziri, Wahbi" },
  { code: "TUN", country: "Tunisia", player: "Khazri, Wahbi" },
  { code: "TUN", country: "Tunisia", player: "Msakni, Youssef" },
  { code: "TUN", country: "Tunisia", player: "Sliti, Ferjani" },
  // Turkey
  { code: "TUR", country: "Turkey", player: "Akturkoglu, Kerem" },
  { code: "TUR", country: "Turkey", player: "Calhanoglu, Hakan" },
  { code: "TUR", country: "Turkey", player: "Under, Cengiz" },
  { code: "TUR", country: "Turkey", player: "Yilmaz, Burak" },
  { code: "TUR", country: "Turkey", player: "Yazici, Yusuf" },
  // United States — Agyemang OUT (Achilles)
  { code: "USA", country: "United States", player: "Balogun, Folarin" },
  { code: "USA", country: "United States", player: "Pepi, Ricardo" },
  { code: "USA", country: "United States", player: "Pulisic, Christian" },
  { code: "USA", country: "United States", player: "Reyna, Giovanni" },
  { code: "USA", country: "United States", player: "Weah, Tim" },
  // Uruguay
  { code: "URU", country: "Uruguay", player: "Cavani, Edinson" },
  { code: "URU", country: "Uruguay", player: "De Arrascaeta, Giorgian" },
  { code: "URU", country: "Uruguay", player: "Núñez, Darwin" },
  { code: "URU", country: "Uruguay", player: "Suárez, Luis" },
  { code: "URU", country: "Uruguay", player: "Valverde, Federico" },
  // Uzbekistan
  { code: "UZB", country: "Uzbekistan", player: "Juraev, Temur" },
  { code: "UZB", country: "Uzbekistan", player: "Masharipov, Dostonbek" },
  { code: "UZB", country: "Uzbekistan", player: "Shomurodov, Eldor" },
  { code: "UZB", country: "Uzbekistan", player: "Sidikov, Jaloliddin" },
  { code: "UZB", country: "Uzbekistan", player: "Tursunov, Otabek" },
];

export function formatScorer(s: { code: string; player: string }): string {
  return `(${s.code}) ${s.player}`;
}
